//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by menu.rc
//
#define MAINMENU                        101
#define IDD_DIALOG1                     102
#define FRM_CONNECT                     102
#define IDD_DIALOGBAR                   103
#define FRM_RAW                         104
#define FRM_ABOUT                       105
#define FRM_MEDIA                       107
#define FRM_PREF_1                      110
#define FRM_PREF_2                      111
#define FRM_CONNECT_SETUP               112
#define FRM_JOIN                        113
#define FRM_CREATE_WINDOW               114
#define FRM_ADD                         115
#define FRM_TOPIC                       116
#define IDC_SERVER                      1000
#define IDC_EDIT2                       1001
#define IDC_PORT                        1001
#define IDC_CHAN                        1001
#define IDC_EDIT3                       1002
#define IDC_NICKNAME                    1002
#define IDC_REALNAME                    1002
#define IDC_EDIT4                       1003
#define IDC_ALTERNATE                   1003
#define IDC_ACONNECT                    1003
#define IDC_NICKNAME2                   1004
#define IDC_CONNECT                     1005
#define IDC_NICKNAME1                   1005
#define IDC_DATA                        1006
#define IDC_EMAIL                       1006
#define IDC_MEDIA                       1008
#define IDC_WALLOPS                     1008
#define IDEXIT                          1009
#define IDC_INVISIBLE                   1009
#define IDPLAY                          1010
#define IDC_SERVMSG                     1010
#define IDC_DIR                         1012
#define IDC_LISTSERVER                  1012
#define IDC_SOUNDDIR                    1013
#define IDC_IRCOP                       1013
#define IDC_LOGDIR                      1014
#define IDC_EDIT1                       1014
#define IDC_LISTNETWORK                 1015
#define IDC_CHANNEL                     1016
#define IDC_CREATEWINDOW                1017
#define IDC_NICK                        1018
#define IDC_OP                          1019
#define IDC_VOICE                       1020
#define IDC_EDIT_SERVLIST               1021
#define IDC_TOPIC                       1021
#define IDC_TYPE1                       1022
#define IDC_TYPE2                       1023
#define IDC_TYPE3                       1024
#define IDC_TYPE4                       1025
#define IDC_DEFQUIT                     1026
#define ID_CONNECT                      40001
#define ID_QUIT                         40002
#define ID_DIRECT                       40003
#define ID_RAW                          40003
#define ID_CASCADE                      40004
#define ID_TILE                         40005
#define ID_ABOUT                        40007
#define ID_MEDIA                        40008
#define ID_PREFS                        40009
#define ID_REINIT                       40011
#define ID_JOINCHANNEL                  40012
#define ID_CREATEWINDOW                 40013
#define ID_ADD                          40014
#define ID_TOPIC                        40015
#define ID_EXPLORATEUR                  40016

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        119
#define _APS_NEXT_COMMAND_VALUE         40019
#define _APS_NEXT_CONTROL_VALUE         1027
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
